name: css_text
description: This library allows you to use simple CSS inline styles to style your text.
version: 2.1.0
homepage: https://github.com/hathibelagal-dev/css_text_for_flutter

environment:
  sdk: ">=2.10.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.3.1

flutter:
