name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  css_text:
    path: ../

flutter:
  uses-material-design: true

